revise README.md

diff --git a/note b/note
--- a/note
+++ b/note
@@ -1,15 +1,16 @@
 #!/bin/bash
+dir=$HOME
+note=myUnixNote
 
 if [ -z $1 ] 
 then
-	ls ~/note | cat
-	for file in *
-		do 
-		 [ -d $file ] && ls $file | cat 
-	done
+	for file in $( find $dir/$note -name "*.note"  )
+		do
+			echo $( basename $file ) | cut -f 1 -d . 
+		done;
 	#印出所有筆記名
 else
-	cat ~/note/$1 2> /dev/null || cat ~/note/BashScript/$1 2> /dev/null || cat ~/note/vimCmd/$1 2> /dev/null || echo "$1 not found"
+	cat ~/$note/$1.note 2> /dev/null || cat ~/$note/BashScript/$1.note 2> /dev/null || cat ~/$note/vimCmd/$1.note 2> /dev/null || echo "$1 not found"
 	#印出所求檔案,利用||原理依次查找
 	#之後可以改成loop 處理	
 fi
